package rules;

import bsep.hospital.logging.LogModel;
import java.util.List;



rule "@{ruleName}"
        no-loop true
    when
        $p: Patient($patId: id, id == @{patientId});
        $ps: PatientStatus($pat: patient, $pat.id == $patId, $t:type, $t.toString() == "@{type}", $val: getValue(), $val @{operation} @{value} );

    then
       modify( $ps ){
           setAlarm(true)
       }
end

end template