package rules;
import bsep.hospital.model.Patient;
import bsep.hospital.model.PatientStatus;
import java.util.List;

rule "MickovoPravilo5"
        agenda-group "doctor-rules"
        no-loop true
    when
        $p: Patient($patId: id, $patId == 1, $bt: bloodType, $bt.toString() == "A_POSITIVE");
        $ps: PatientStatus($pat: patient, $pat.id == $patId);
    then
       modify( $ps ){
           setAlarm(true)
       }
end


