package rules;
import bsep.hospital.model.Patient;
import bsep.hospital.model.PatientStatus;
import java.util.List;

rule "MickovoPravilo3"
        agenda-group "doctor-rules"
        no-loop true
    when
        $p: Patient($patId: id, id == 1, $bt: bloodType, $bt.toString() == "A_POSITIVE");
        $ps: PatientStatus($pat: patient, $pat.id == $patId, $t:type, $t.toString() == "HEARTH_BEAT", $val: getValue(), $val != 10.0 );
    then
       modify( $ps ){
           setAlarm(true)
       }
end


